# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: mobagel/airflow

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        env:
          AIRFLOW_GPL_UNIDECODE: yes
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            AIRFLOW_VERSION=2.6.2
            AIRFLOW_EXTRAS=async,celery,cncf.kubernetes,dask,docker,grpc,http,ldap,postgres,redis,statsd,virtualenv
            PYTHON_BASE_IMAGE=python:3.8-slim-bullseye
            ADDITIONAL_PYTHON_DEPS=scikit-learn==1.0.2 slack-sdk==3.21.3 pyjanitor==0.22.0 glom==22.1.0 yfinance==0.1.70 pandas-datareader==0.10.0 awesome-object-store>=2.2.1 ShopifyAPI==12.2.0 networkx>=2.5 google-cloud-bigquery==2.34.4 db-dtypes>=1.0.0 klaviyo_sdk==1.0.6.20220329 sqlparse==0.4.3 pytest==7.1.3 pytest-html==3.2.0 apache-airflow-providers-google==8.8.0 kubernetes==23.6.0 google-api-core==2.8.2 junitparser==3.1.0 apache-airflow-providers-sftp==4.3.0 airtable>=0.4.8
